improve scripts

diff --git a/st-urlhandler b/st-urlhandler
--- a/st-urlhandler
+++ b/st-urlhandler
@@ -1,19 +1,37 @@
 #!/bin/sh
 
-urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"
+if [ $# -eq 0 ] || [ "$1" = "-h" ]; then
+	printf "usage:\n\t-c: copy\n\t-o: xdg-open\n\t-h: help\n"
+	exit 1
+fi
 
-urls="$(sed 's/.*│//g' | tr -d '\n' | # First remove linebreaks and mutt sidebars:
-	grep -aEo "$urlregex" | # grep only urls as defined above.
-	uniq | # Ignore neighboring duplicates.
-	sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
-	s/^www./http:\/\/www\./")" # xdg-open will not detect url without http
+urls="$(
+	# remove linebreaks and mutt sidebars
+	sed "s/.*│//g" | tr -d "\n" |
+	# grep urls
+	grep -aEo "(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)" |
+	# ignore duplicates
+	uniq |
+	# xdg-open will not detect url without http
+	sed "s/\(\.\|,\|;\|\!\\|\?\)$//;s/^www./http:\/\/www\./"
+)"
 
 [ -z "$urls" ] && exit 1
 
-while getopts "hoc" o; do case "${o}" in
-	h) printf "Optional arguments for custom use:\\n  -c: copy\\n  -o: xdg-open\\n  -h: Show this message\\n" && exit 1 ;;
-	o) chosen="$(echo "$urls" | dmenu -i -p 'Follow which url?' -l 10)"
-	setsid xdg-open "$chosen" >/dev/null 2>&1 & ;;
-	c) echo "$urls" | dmenu -i -p 'Copy which url?' -l 10 | tr -d '\n' | xclip -selection clipboard ;;
-	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
-esac done
+while [ $# != 0 ]; do
+	case "$1" in
+		-c)
+			echo "$urls" | dmenu -i -p "copy url:" -l 10 | tr -d "\n" | xclip -sel clip
+			;;
+		-o)
+			sel="$(echo "$urls" | dmenu -i -p "open url:" -l 10)"
+			[ -z "$sel" ] && exit 1
+			setsid xdg-open "$sel" >/dev/null 2>&1 &
+			;;
+		*)
+			printf "invalid option: -%s\n" "$1"
+			exit 1
+			;;
+	esac
+	shift
+done
